using UnityEngine;
using UnityEngine.Video;
using UnityEngine.UI;

public class TriggerVideoPlayer : MonoBehaviour
{
    [Header("Video")]
    [SerializeField] private VideoPlayer videoPlayer;

    [Header("Screen")]
    [SerializeField] private RawImage videoScreen;

    [Header("Trigger Settings")]
    [SerializeField] private bool playOnlyOnce = true;

    private bool hasPlayed = false;

    private void Start()
    {
        // Make sure the video screen starts hidden.
        if (videoScreen != null)
        {
            videoScreen.gameObject.SetActive(false);
        }

        // Make sure the video does not automatically start.
        if (videoPlayer != null)
        {
            videoPlayer.playOnAwake = false;

            // API Only allows us to access the video through
            // videoPlayer.texture.
            videoPlayer.renderMode = VideoRenderMode.APIOnly;

            // When the video is prepared, assign its texture
            // to the Raw Image.
            videoPlayer.prepareCompleted += OnVideoPrepared;

            // When the video finishes, hide the screen.
            videoPlayer.loopPointReached += OnVideoFinished;
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        // Only activate when the PLAYER enters.
        if (!other.CompareTag("Player"))
            return;

        if (playOnlyOnce && hasPlayed)
            return;

        hasPlayed = true;

        PlayVideo();
    }

    private void PlayVideo()
    {
        if (videoPlayer == null)
        {
            Debug.LogError("Video Player has not been assigned!");
            return;
        }

        if (videoScreen == null)
        {
            Debug.LogError("Video Screen Raw Image has not been assigned!");
            return;
        }

        // Show the video screen.
        videoScreen.gameObject.SetActive(true);

        // Reset the video to the beginning.
        videoPlayer.Stop();
        videoPlayer.time = 0;

        // Prepare the video.
        videoPlayer.Prepare();
    }

    private void OnVideoPrepared(VideoPlayer player)
    {
        // Give the Raw Image the texture generated by the Video Player.
        if (videoScreen != null)
        {
            videoScreen.texture = player.texture;
        }

        // Start playing.
        player.Play();
    }

    private void OnVideoFinished(VideoPlayer player)
    {
        // Hide the video screen when the video finishes.
        if (videoScreen != null)
        {
            videoScreen.gameObject.SetActive(false);
        }

        Debug.Log("Video finished.");
    }

    private void OnDestroy()
    {
        if (videoPlayer != null)
        {
            videoPlayer.prepareCompleted -= OnVideoPrepared;
            videoPlayer.loopPointReached -= OnVideoFinished;
        }
    }
}